import type { Lead, Task, Activity, EmailSequence, Workflow, Meeting, Offer, Proposal, Invoice } from "./types"

// Mock Leads Data
export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "Sarah Chen",
    email: "sarah.chen@techcorp.com",
    phone: "+1 (555) 123-4567",
    company: "TechCorp",
    stage: "qualified",
    moodScore: "positive",
    moodConfidence: 85,
    source: "Website Form",
    tags: ["enterprise", "high-value"],
    owner: "John Doe",
    createdAt: new Date("2024-12-01"),
    lastActivity: new Date("2024-12-20"),
  },
  {
    id: "2",
    name: "Mike Johnson",
    email: "mike.j@startupxyz.io",
    phone: "+1 (555) 234-5678",
    company: "StartupXYZ",
    stage: "replied",
    moodScore: "neutral",
    moodConfidence: 60,
    source: "LinkedIn",
    tags: ["startup", "tech"],
    owner: "John Doe",
    createdAt: new Date("2024-12-05"),
    lastActivity: new Date("2024-12-19"),
  },
  {
    id: "3",
    name: "Emma Wilson",
    email: "emma@agencyplus.com",
    phone: "+1 (555) 345-6789",
    company: "Agency Plus",
    stage: "call_booked",
    moodScore: "positive",
    moodConfidence: 90,
    source: "Referral",
    tags: ["agency", "marketing"],
    owner: "John Doe",
    createdAt: new Date("2024-12-10"),
    lastActivity: new Date("2024-12-21"),
  },
  {
    id: "4",
    name: "John Smith",
    email: "jsmith@enterprise.co",
    phone: "+1 (555) 456-7890",
    company: "Enterprise Co",
    stage: "contacted",
    moodScore: "unknown",
    moodConfidence: 30,
    source: "Cold Outreach",
    tags: ["enterprise"],
    owner: "John Doe",
    createdAt: new Date("2024-12-08"),
    lastActivity: new Date("2024-12-15"),
  },
  {
    id: "5",
    name: "Lisa Park",
    email: "lisa@designstudio.com",
    phone: "+1 (555) 567-8901",
    company: "Design Studio",
    stage: "proposal_sent",
    moodScore: "positive",
    moodConfidence: 75,
    source: "Website Form",
    tags: ["design", "creative"],
    owner: "John Doe",
    createdAt: new Date("2024-11-28"),
    lastActivity: new Date("2024-12-18"),
  },
  {
    id: "6",
    name: "Tom Brown",
    email: "tom.brown@consulting.inc",
    phone: "+1 (555) 678-9012",
    company: "Consulting Inc",
    stage: "invoice_sent",
    moodScore: "positive",
    moodConfidence: 95,
    source: "Referral",
    tags: ["consulting", "b2b"],
    owner: "John Doe",
    createdAt: new Date("2024-11-15"),
    lastActivity: new Date("2024-12-17"),
  },
  {
    id: "7",
    name: "Alex Rivera",
    email: "alex@freelance.dev",
    company: "Freelance Dev",
    stage: "new",
    moodScore: "unknown",
    moodConfidence: 0,
    source: "Website Form",
    tags: ["developer"],
    createdAt: new Date("2024-12-20"),
    lastActivity: new Date("2024-12-20"),
  },
  {
    id: "8",
    name: "Nina Patel",
    email: "nina@ecommstore.com",
    phone: "+1 (555) 789-0123",
    company: "E-comm Store",
    stage: "presented",
    moodScore: "neutral",
    moodConfidence: 55,
    source: "Google Ads",
    tags: ["ecommerce", "retail"],
    owner: "John Doe",
    createdAt: new Date("2024-12-02"),
    lastActivity: new Date("2024-12-19"),
  },
  {
    id: "9",
    name: "David Kim",
    email: "david.kim@fintech.io",
    phone: "+1 (555) 890-1234",
    company: "FinTech Solutions",
    stage: "nurture",
    moodScore: "negative",
    moodConfidence: 70,
    source: "LinkedIn",
    tags: ["fintech", "long-cycle"],
    owner: "John Doe",
    createdAt: new Date("2024-10-15"),
    lastActivity: new Date("2024-12-10"),
  },
  {
    id: "10",
    name: "Rachel Green",
    email: "rachel@mediagroup.com",
    phone: "+1 (555) 901-2345",
    company: "Media Group",
    stage: "won",
    moodScore: "positive",
    moodConfidence: 100,
    source: "Referral",
    tags: ["media", "advertising"],
    owner: "John Doe",
    createdAt: new Date("2024-11-01"),
    lastActivity: new Date("2024-12-15"),
  },
]

// Mock Activities
export const mockActivities: Activity[] = [
  {
    id: "1",
    leadId: "1",
    type: "email_sent",
    title: "Follow-up Email",
    description: "Sent follow-up email regarding proposal discussion",
    createdAt: new Date("2024-12-20T10:30:00"),
  },
  {
    id: "2",
    leadId: "1",
    type: "email_received",
    title: "Reply Received",
    description: "Sarah replied expressing interest in the enterprise package",
    createdAt: new Date("2024-12-20T14:15:00"),
  },
  {
    id: "3",
    leadId: "1",
    type: "meeting",
    title: "Discovery Call Completed",
    description: "30-minute discovery call to understand requirements",
    metadata: { duration: 30, type: "discovery" },
    createdAt: new Date("2024-12-18T11:00:00"),
  },
  {
    id: "4",
    leadId: "1",
    type: "stage_change",
    title: "Stage Changed",
    description: "Moved from Contacted to Qualified",
    createdAt: new Date("2024-12-18T11:35:00"),
  },
  {
    id: "5",
    leadId: "1",
    type: "note",
    title: "Call Notes",
    description:
      "Sarah mentioned they are evaluating 3 vendors. Budget approved for Q1. Key decision maker is their CTO.",
    createdAt: new Date("2024-12-18T11:40:00"),
  },
]

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: "1",
    leadId: "1",
    type: "call",
    title: "Follow-up call with Sarah",
    description: "Discuss proposal details and answer questions",
    status: "pending",
    dueDate: new Date("2024-12-22T10:00:00"),
    createdAt: new Date("2024-12-20"),
  },
  {
    id: "2",
    leadId: "2",
    type: "email",
    title: "Send case study",
    description: "Share relevant case study from similar industry",
    status: "pending",
    dueDate: new Date("2024-12-22T14:00:00"),
    createdAt: new Date("2024-12-19"),
  },
  {
    id: "3",
    leadId: "3",
    type: "follow_up",
    title: "Prepare demo presentation",
    status: "pending",
    dueDate: new Date("2024-12-23T09:00:00"),
    createdAt: new Date("2024-12-21"),
  },
]

// Mock Email Sequences
export const mockSequences: EmailSequence[] = [
  {
    id: "1",
    name: "New Lead Welcome",
    status: "active",
    steps: [
      { id: "s1", type: "email", templateId: "t1" },
      { id: "s2", type: "delay", delayDays: 3 },
      { id: "s3", type: "email", templateId: "t2" },
    ],
    enrolledCount: 48,
    replyRate: 24,
    createdAt: new Date("2024-11-01"),
  },
  {
    id: "2",
    name: "Post-Call Follow-up",
    status: "active",
    steps: [
      { id: "s1", type: "email", templateId: "t3" },
      { id: "s2", type: "delay", delayDays: 2 },
      { id: "s3", type: "condition", condition: "no_reply" },
      { id: "s4", type: "email", templateId: "t4" },
    ],
    enrolledCount: 22,
    replyRate: 45,
    createdAt: new Date("2024-11-15"),
  },
  {
    id: "3",
    name: "Re-engagement",
    status: "paused",
    steps: [
      { id: "s1", type: "email", templateId: "t5" },
      { id: "s2", type: "delay", delayDays: 7 },
      { id: "s3", type: "email", templateId: "t6" },
    ],
    enrolledCount: 156,
    replyRate: 8,
    createdAt: new Date("2024-10-20"),
  },
]

// Mock Workflows
export const mockWorkflows: Workflow[] = [
  {
    id: "1",
    name: "New Lead Auto-Enroll",
    trigger: { type: "lead_created" },
    conditions: [{ field: "email", operator: "contains", value: "@" }],
    actions: [{ type: "enroll_sequence", config: { sequenceId: "1" } }],
    status: "active",
    mode: "autopilot",
    lastRun: new Date("2024-12-21T08:30:00"),
    failedRuns: 0,
  },
  {
    id: "2",
    name: "Meeting Completed Workflow",
    trigger: { type: "meeting_completed" },
    conditions: [],
    actions: [
      { type: "create_task", config: { type: "follow_up", title: "Send proposal" } },
      { type: "enroll_sequence", config: { sequenceId: "2" } },
    ],
    status: "active",
    mode: "assisted",
    lastRun: new Date("2024-12-20T15:00:00"),
    failedRuns: 1,
  },
]

// Mock Meetings
export const mockMeetings: Meeting[] = [
  {
    id: "1",
    leadId: "3",
    type: "demo",
    title: "Product Demo with Emma",
    scheduledAt: new Date("2024-12-22T10:00:00"),
    duration: 45,
    location: "Google Meet",
    meetingLink: "https://meet.google.com/abc-defg-hij",
    status: "scheduled",
  },
  {
    id: "2",
    leadId: "8",
    type: "presentation",
    title: "Presentation Call with Nina",
    scheduledAt: new Date("2024-12-22T14:00:00"),
    duration: 60,
    location: "Zoom",
    meetingLink: "https://zoom.us/j/123456789",
    status: "scheduled",
  },
]

// Mock Offers
export const mockOffers: Offer[] = [
  {
    id: "1",
    type: "package",
    name: "Starter Package",
    description: "Perfect for solo founders and small teams",
    price: 499,
    currency: "USD",
    deliverables: ["CRM Setup", "Email Integration", "5 Automations", "Email Support"],
  },
  {
    id: "2",
    type: "package",
    name: "Growth Package",
    description: "For growing businesses with active sales teams",
    price: 999,
    currency: "USD",
    deliverables: ["Everything in Starter", "Unlimited Automations", "Calendar Integration", "Priority Support"],
  },
  {
    id: "3",
    type: "package",
    name: "Enterprise Package",
    description: "Full-featured solution for large teams",
    price: 2499,
    currency: "USD",
    deliverables: ["Everything in Growth", "Custom Integrations", "Dedicated Account Manager", "SLA"],
  },
]

// Mock Proposals
export const mockProposals: Proposal[] = [
  {
    id: "1",
    leadId: "5",
    templateId: "1",
    offers: [mockOffers[1]],
    customItems: [{ name: "Custom Branding", price: 200 }],
    totalAmount: 1199,
    status: "sent",
    createdAt: new Date("2024-12-16"),
    sentAt: new Date("2024-12-16"),
  },
  {
    id: "2",
    leadId: "6",
    templateId: "1",
    offers: [mockOffers[2]],
    customItems: [],
    totalAmount: 2499,
    status: "accepted",
    createdAt: new Date("2024-12-10"),
    sentAt: new Date("2024-12-10"),
  },
]

// Mock Invoices
export const mockInvoices: Invoice[] = [
  {
    id: "1",
    leadId: "6",
    proposalId: "2",
    items: [{ name: "Enterprise Package", quantity: 1, unitPrice: 2499 }],
    subtotal: 2499,
    tax: 0,
    total: 2499,
    status: "sent",
    dueDate: new Date("2024-12-31"),
    paymentLink: "https://pay.stripe.com/xyz",
    createdAt: new Date("2024-12-15"),
  },
]

export const stageLabels: Record<string, string> = {
  new: "New",
  contacted: "Contacted",
  replied: "Replied",
  qualified: "Qualified",
  call_booked: "Call Booked",
  presented: "Presented",
  proposal_sent: "Proposal Sent",
  invoice_sent: "Invoice Sent",
  won: "Won",
  lost: "Lost",
  nurture: "Nurture",
}

export const stageColors: Record<string, string> = {
  new: "bg-chart-5",
  contacted: "bg-chart-2",
  replied: "bg-chart-1",
  qualified: "bg-primary",
  call_booked: "bg-chart-3",
  presented: "bg-chart-4",
  proposal_sent: "bg-warning",
  invoice_sent: "bg-chart-1",
  won: "bg-success",
  lost: "bg-destructive",
  nurture: "bg-muted-foreground",
}

export const moodColors: Record<string, string> = {
  positive: "text-success bg-success/10",
  neutral: "text-warning bg-warning/10",
  negative: "text-destructive bg-destructive/10",
  unknown: "text-muted-foreground bg-muted",
}
